# <h1><center>**FUNCIONES ELEMENTALES DE NUMPY**</center></h1>



### Introducción


NumPy es una librería que proporciona una estructura de datos en forma matricial y que tiene varias ventajas sobre las listas normales de Python.


Esto se puede comprobar en el siguiente ejemplo:


In [3]:
import numpy as np
import sys, time

In [2]:
S = range(1000)
print("Resultado memoria ocupada listas de Python:")
print(f'{sys.getsizeof(5)*len(S)}' + "\n")
D = np.arange(1000)
print("Resultado memoria ocupada Numpy array:")
print(f'{D.size*D.itemsize}' + "\n")


SIZE = 1000000
L1 = range(SIZE)
L2 = range(SIZE)
A1 = np.arange (SIZE)
A2 = np.arange (SIZE)
start = time.time()
result=[(x,y) for x,y in zip(L1,L2)]
print("Resultado tiempo listas de Pyhton")
print(f'{(time.time()-start)*1000}' + " ms\n")
start = time.time()
result=A1+A2
print("Resultado tiempo Numpy array:")
print(f'{(time.time()-start)*1000}' + " ms")

Resultado memoria ocupada listas de Python:
28000

Resultado memoria ocupada Numpy array:
4000

Resultado tiempo listas de Pyhton
277.9374122619629 ms

Resultado tiempo Numpy array:
49.69501495361328 ms


Como se puede comprobar, las matrices de NumPy son más rápidas y ocupan menos memoria. Esto se debe a que esta librería está optimizada para trabajar con matrices.




### Cómo usar NumPy



+ Crear una matriz 1D y 2D:


In [3]:
print("Crear una matriz 1D y 2D")
b = np.array([1,2,3])
print("1D array:")
print(b)
b = np.array([ (1,2,3), (4,5,6) ])
print("2D array:")
print(b)

Crear una matriz 1D y 2D
1D array:
[1 2 3]
2D array:
[[1 2 3]
 [4 5 6]]


+ Crear matrices de ceros, vacías, random y de un solo valor


In [7]:
print("Crear matrices de ceros, vacías y random")
ceros = np.zeros((3,4))
print(f'{ceros}' + "\n")
empty = np.empty((3,4))
print(f'{empty}' + "\n")
random = np.random.random((3,4))
print(f'{random}' + "\n")
full = np.full((3,4), 7)
print(f'{full}')

Crear matrices de ceros, vacías y random
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

[[0.44239169 0.06590335 0.67627295 0.00712602]
 [0.88339864 0.16195002 0.90447657 0.57299399]
 [0.38363804 0.03561679 0.67585772 0.17230578]]

[[7 7 7 7]
 [7 7 7 7]
 [7 7 7 7]]


IndexError: index 10 is out of bounds for axis 0 with size 10

+ Crear matrices con valores espaciados uniformemente


In [5]:
print("Crear matriz con valores espaciados uniformemente")
espacio1 = np.arange(1,15,1) #Comienzo, fin y paso
print(f'{espacio1}' + "\n")
espacio2 = np.linspace(0,2,5) #Matriz entre 0 y 2 con 5 valores
print(f'{espacio2}')

Crear matriz con valores espaciados uniformemente
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[0.  0.5 1.  1.5 2. ]


+ Crear matriz de unos en la diagonal


In [6]:
print("Crear matriz de unos en la diagonal")
identidad1 = np.eye(4,3) # Crea matriz con unos en la diagonal 
print(f'{identidad1}' + "\n")
identidad2 = np.identity(4) # Crea matriz identidad
print(f'{identidad2}')

Crear matriz de unos en la diagonal
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]
 [0. 0. 0.]]

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


+ Conocer la dimensión, forma, tipo de dato y memoria ocupada de una matriz


In [7]:
print("Conocer la dimensión, forma, tipo de dato y memoria ocupada de una matriz")
a = np.full((2,3,5), 100)
dim = a.ndim
size = a.size
shape = a.shape
tipo = a.dtype
mem = a.nbytes
print(f'{a}')
print("\tDimensión: " + f'{dim}')
print("\tTamaño: " + f'{size}')
print("\tForma: " + f'{shape}')
print("\tTipo de dato: " + f'{tipo}')
print("\tMemoria ocupada: " + f'{mem}' + " bytes")

Conocer la dimensión, forma, tipo de dato y memoria ocupada de una matriz
[[[100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]]

 [[100 100 100 100 100]
  [100 100 100 100 100]
  [100 100 100 100 100]]]
	Dimensión: 3
	Tamaño: 30
	Forma: (2, 3, 5)
	Tipo de dato: int32
	Memoria ocupada: 120 bytes


+ Operaciones con matrices


In [9]:
print("Operaciones con matrices")
a = np.array([ (100,1,2,3,4), (5,6,7,8,9), (10,11,12,13,14), (16,17,18,19,20), (21,22,23,24,25)])
print(a)

print("\n- Extraer un solo valor:")
only_value = a[1,3]
print("\tFila 1, columna 3: " + f'{only_value}' + "\n")

print("\n- Extraer todas las filas de una columna:")
fila = a[0:,3] # Valores de la columna 2 desde la fila 0 hasta el final
print("\tValores de la columna 3: " + f'{fila}' + "\n")

print("\n- Valores mínimos, máximos y suma de valores de una matriz:")
min = a.min()
max = a.max()
sum = a.sum()
print("\tValor mínimo: " + f'{min}')
print("\tValor máximo: " + f'{max}')
print("\tSuma de valores: " + f'{sum}')

print("\n- Suma, resta, multiplicación, división, riz cuadrada y desviación estándar:")
i = np.identity(5)
print("\tSuma:\n" + f'{a+i}' + "\n")
print("\tResta:\n" + f'{a-i}' + "\n")
print("\tMultiplicación escalar:\n" + f'{a*i}' + "\n")
print("\tMultiplicación matricial:\n" + f'{np.dot(a,i)}' + "\n")
print("\tDivisión:\n" + f'{i/a}' + "\n")
print("\tRaíz cuadrada:\n" + f'{np.sqrt(a)}' + "\n")
print("\tDesviación estándar: " + f'{np.std(a)}')

Operaciones con matrices
[[100   1   2   3   4]
 [  5   6   7   8   9]
 [ 10  11  12  13  14]
 [ 16  17  18  19  20]
 [ 21  22  23  24  25]]

- Extraer un solo valor:
	Fila 1, columna 3: 8


- Extraer todas las filas de una columna:
	Valores de la columna 3: [ 3  8 13 19 24]


- Valores mínimos, máximos y suma de valores de una matriz:
	Valor mínimo: 1
	Valor máximo: 100
	Suma de valores: 410

- Suma, resta, multiplicación, división, riz cuadrada y desviación estándar:
	Suma:
[[101.   1.   2.   3.   4.]
 [  5.   7.   7.   8.   9.]
 [ 10.  11.  13.  13.  14.]
 [ 16.  17.  18.  20.  20.]
 [ 21.  22.  23.  24.  26.]]

	Resta:
[[99.  1.  2.  3.  4.]
 [ 5.  5.  7.  8.  9.]
 [10. 11. 11. 13. 14.]
 [16. 17. 18. 18. 20.]
 [21. 22. 23. 24. 24.]]

	Multiplicación escalar:
[[100.   0.   0.   0.   0.]
 [  0.   6.   0.   0.   0.]
 [  0.   0.  12.   0.   0.]
 [  0.   0.   0.  19.   0.]
 [  0.   0.   0.   0.  25.]]

	Multiplicación matricial:
[[100.   1.   2.   3.   4.]
 [  5.   6.   7.   8.   9.]
 [

In [ ]:
# TRANSFORMADA RÁPIDA DE FOURIER EN TIEMPO DISCRETO

import matplotlib.pyplot as plt
import numpy as np

N = 500 #Nº DE MUESTRAS
T = 1.0 / 600.0
x = np.linspace(0.0, N*T, N)
y = np.sin(60.0 * 2.0*np.pi*x) + 0.5*np.sin(90.0 * 2.0*np.pi*x)
y_f = np.fft.fft(y)
x_f = np.linspace(0.0, 1.0/(2.0*T), N//2)

plt.plot(x_f, 2.0/N * np.abs(y_f[:N//2]))
plt.show()